### ISSUE TITLE
Handling of nested 'html' documents

### ISSUE THREAD

**Issue by TheCBaH** [aantron/markup.ml#28]
Apparently markup.ml  doesn't handle nested html documents (e.g. html document inserted into middle of another html document), currently markup.ml just silently ignores everything after the first closing `</html>` tag. 

There is a quick example of such behavior:
``` ML
let _ =
  let open Markup in
  string "<html><body><div id=foo><html></html>FOO</div><div id=bar>BAR</div></body></html>"
  |> parse_html
  |> signals
  |> write_html
  |> to_channel stdout
```
`<html><head></head><body><div id="foo"></div></body></html>`

It's understood, that HTML document nesting is outside of any HTML specification, however its handled by all major browsers as well as by JS parsers.

For example there is link to parsing tree generater by https://github.com/inikulin/parse5 :
https://astexplorer.net/#/gist/16f24683fd56e8f65bf8beb8f6c8664d/latest

**Comment by aantron** [comment]
Hmmm, when I expanded the AST, I didn't see a nested `<html>` element:

![captura de pantalla 2017-12-29 a la s 09 42 17](https://user-images.githubusercontent.com/12073668/34439537-b5d5034c-ec7c-11e7-9716-174c9173add8.png)

I think you are referring not to allowing nested HTML elements, but to recovering from closing nested `</html>` tags, when they are preceded by an opening `<html>` tag (which remains a parse error) without ending the document. I guess we could support this.

For our own reference later, this is actually positively against the [HTML spec](https://www.w3.org/TR/html5/syntax.html#the-in-body-insertion-mode):

> A start tag whose tag name is "body"
Parse error.
>
> If the second element on the stack of open elements is not a body element, if the stack of open elements has only one node on it, or if there is a template element on the stack of open elements, then ignore the token. (fragment case)
>
> Otherwise, set the frameset-ok flag to "not ok"; then, for each attribute on the token, check to see if the attribute is already present on the body element (the second element) on the stack of open elements, and if it is not, add the attribute and its corresponding value to that element.

This says (in the common case) to add any new attributes on a nested `<html>` tag to the top-level tag, which will often be an `<html>` tag (which Markup.ml doesn't do either), and otherwise ignore the nested `<html>` tag.

> An end tag whose tag name is "html"
If the stack of open elements does not have a body element in scope, this is a parse error; ignore the token.
>
> Otherwise, if there is a node in the stack of open elements that is not either a dd element, a dt element, an li element, an optgroup element, an option element, a p element, an rb element, an rp element, an rt element, an rtc element, a tbody element, a td element, a tfoot element, a th element, a thead element, a tr element, the body element, or the html element, then this is a parse error.
>
> Switch the insertion mode to "after body".
>
> Reprocess the token.

This eventually causes the entire document to end when `</html>` is seen, after closing enclosing elements.

The `<html>` start tag in `<body>` is handled here: 

https://github.com/aantron/markup.ml/blob/d2905e3ccf1abeac5314e24293d0bec47f23a6ad/src/html_parser.ml#L1638-L1639

I think we need to change that to insert a fake "nested HTML" element into the stack, that won't compare equal with real HTML elements (so we don't mess up the standards-compliance of the rest of the parser). We need to still not emit a parsing signal for it, though.

The `</html>` end tag in `<body>` is handled here:

https://github.com/aantron/markup.ml/blob/d2905e3ccf1abeac5314e24293d0bec47f23a6ad/src/html_parser.ml#L1689-L1698

We should probably change this to check for whether the top element on the stack is the fake "nested HTML" element. If so, we pop it and continue parsing, otherwise we run the code that is already there.

I haven't thought through how having this "nested HTML" element will interact with the rest of HTML5 error recovery.

Also, FYI, Markup.ml doesn't silently ignore things after `</html>`. If you use the `~report` callback of `parse_html`, you will see that it reports errors, as required by HTML5:

```ocaml
let _ =
  let open Markup in
  string "<html><body><div id=foo><html></html>FOO</div><div id=bar>BAR</div></body></html>"
  |> parse_html ~report:(fun location error -> Error.to_string ~location error |> prerr_endline)
  |> signals
  |> write_html
  |> to_channel stdout
```

results in

```
line 1, column 25: misnested tag: 'html' in 'body'
line 1, column 13: unmatched start tag 'div'
line 1, column 38: bad content in 'html'
line 1, column 39: bad content in 'html'
line 1, column 40: bad content in 'html'
line 1, column 41: bad content in 'html'
line 1, column 47: bad content in 'html'
line 1, column 59: bad content in 'html'
line 1, column 60: bad content in 'html'
line 1, column 61: bad content in 'html'
line 1, column 62: bad content in 'html'
line 1, column 68: bad content in 'html'
line 1, column 75: bad content in 'html'
```

It's arguably too literal to the spec and too noisy (probably because few people have used error reporting to date), but the first error reveals the problem.

**Comment by TheCBaH** [comment]
>Also, FYI, Markup.ml doesn't silently ignore things after </html>.

Right, Markup.ml reports an parsing errors in all erogenous cases (extra `<html>`, out of scope `</html>` and `<div>` after `</html>`. However there is no much practical error handle could do to actually recover from errors and let Markup.ml parse html after stray `</html>`. And users of libraries that rely on Markup.ml (like Soup) could do nothing to process such html files.

>I think we need to change that to insert a fake "nested HTML" element into the stack, that won't compare equal with real HTML elements (so we don't mess up the standards-compliance of the rest of the parser). We need to still not emit a parsing signal for it, though.

Well, this was also my initial though, however it seems to be rather complicated. It turns out there are is a much simple practical approach, since stray extra `<html>` and  `<body>`  are already ignored, it should be enough to ignore non terminating `</html>` and `</body>` to achieve similar results, so there is #29.

P.S. It appears that JS parser5 pretty much ignores  `</html>` and `</body>`
https://astexplorer.net/#/gist/c3c279e6505abbfb04189f35abd9f1f9/latest  .

**Comment by TheCBaH** [comment]
Superseded by #30

**Comment by aantron** [comment]
Hey, I think you meant to close the PR #29, not this :) But it's ok :)

I'm going to look into the `</body>` example today or tomorrow, and add it to #30, and that hopefully will resolve this issue.
