### ISSUE TITLE
Displaced whitespaces for html/body.

### ISSUE THREAD

**Issue by Drup** [aantron/markup.ml#32]
I discovered that one because it made tyxml's tests fail:

```ocaml
# open Markup 
# to_string @@ write_html @@ signals @@ parse_html @@ string 
    "  <html><head><title>foo</title></head><body></body></html>  "  ;;
- : string = "<html><head><title>foo</title></head><body>  </body></html>"
```
The whitespaces after html (which, according to the spec, are not relevant for parsing) are moved to inside the body (where, iirc, they are relevant).

**Comment by Drup** [comment]
Another similar one from the tyxml tests: `"<html><head><title>foo</title></head> </html>"` used to be parsed `"<html><head><title>foo</title></head><body></body></html>"` but is now parsed `"<html><head><title>foo</title></head><body>  </body></html>"`.

**Comment by aantron** [comment]
I believe Markup.ml is parsing correctly in the first example. The old, at first glance more reasonable behavior was fixed in #28 and #30.

For comparison, see the output of parse5: https://astexplorer.net/#/gist/a57dce947fc085c1c2a77f6f6190dd74/187cdfb9d84a6b227a9fa445c01c24e126665404

Assuming we are starting in between `<body>` and `</body>`, the parser mode will be "[in body](http://www.w3.org/TR/html52/syntax.html#the-in-body-insertion-mode)." The `</body>` token will change it to "[after body](http://www.w3.org/TR/html52/syntax.html#the-after-body-insertion-mode)," *without popping the `<body>` element*, and the `</html>` token to "[after after body](http://www.w3.org/TR/html52/syntax.html#the-after-after-body-insertion-mode)." At this point, the parser sees the whitespace, and it is supposed to process it using the rules of "in body," which eventually means adding them to the current node, which is still the `<body>` element because it was never popped.

Markup.ml looks wrong about the second example, looking into it.

**Comment by aantron** [comment]
Yeah, this is pretty much crazy. It looks like the HTML5 authors eventually gave up and decided to pretty much ignore `</body>` and `</html>`, i.e. the `<body>` continues until the end of document, and these "after body" modes exist only to tell people that their HTML is malformed before resuming processing the "body."

The only thing that actually pops `<body>` and `<html>` elements is the end of input, IIRC.

**Comment by aantron** [comment]
@Drup, I can't reproduce the other issue in `master`. I added it as a test (see above commit), but Markup.ml generates

```html
<html><head><title>foo</title></head> <body></body></html>
```

which is correct w.r.t. the spec AFAICT.

**Comment by Drup** [comment]
hmm, I might have screwed up something on the way. It seems these bugs are mostly feature, and tyxml should respect them, so let's close!
