### ISSUE TITLE
<noscript> element gets wrapped in <body> in partial documents 

### ISSUE THREAD

**Issue by dmbaturin** [aantron/markup.ml#48]
Just like the `<script>` element, `<noscript>` is allowed in both the `<head>` and the `<body>` elements [[1]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript). Thus it's impossible to make assumptions whether we are in the head or the body judging by the `<noscript>` element alone.

However, that's what the parser seems to be doing. If you give it a partial document without head or body tags, it inserts a `<body>` element and wraps the `<noscript>` element in it. It doesn't move any script tags or wrap them in a `<head>` though.

```
utop # Soup.parse "<script src='/scripts/foo.js'></script> <noscript>JS is disabled</noscript>" |> Soup.pretty_print |> print_endline;;
<script src="/scripts/foo.js"></script>
<noscript></noscript>
<body>
 JS is disabled
</body>

- : unit = ()
```

A `<script>` element doesn't trigger that behaviour and gets parsed as partial HTML without assumptions. I believe `<noscript> ` should behave the same.

**Comment by aantron** [comment]
I'm still trying to re-learn how to interpret certain parts of the HTML5 spec for this issue. IIRC, what is happening is that Markup.ml is interpreting `<noscript>` without context information to be in an implicit `<head>`, so that is why its content ends up moved out to `<body>`. I'm just not sure if this is according to the spec anymore, but there is an explicit test for this:

https://github.com/aantron/markup.ml/blob/e2de29fa3deb216562b8357f9a4a3a4fcf397a00/test/test_html_parser.ml#L898-L909

Also note that

```html
<body><noscript>foo</noscript></body>
```

is parsed "normally."

If the current behavior *is* according to the spec, it seems like quite a pain, so we might have to deviate from the spec deliberately.

**Comment by aantron** [comment]
Also, just removing mention of `noscript` from this pattern:

https://github.com/aantron/markup.ml/blob/e2de29fa3deb216562b8357f9a4a3a4fcf397a00/src/html_parser.ml#L184-L187

might be enough for a fix. As I recall, that matching is not according to the spec, but is rather my attempt to make the `~context` parameter of the parser optional by trying to guess the right context for the user in most cases.

If you remove `noscript`, the context will be inferred as `` `Fragment "body" ``, which is probably more reasonable for `noscript`. Would you like to try that while I look through the spec some more (the reason I need to is because I suspect some parts have changed, as they don't look very familiar anymore)?

**Comment by aantron** [comment]
(It may also be good to remove `script` from the pattern, this will handle the case `<script></script><noscript></noscript>`; only removing `<noscript>` from the pattern will still cause that fragment to be parsed as if it is inside `<head>`. The difference in the handling between the two in `<head>` is due to the difference between the handling of inner content. More is allowed in `<script>` than in `<noscript>` that appears in `<head>`, because `<script>` allows basically any text, but `<noscript>` allows what the surrounding context allows).

**Comment by dmbaturin** [comment]
If my understanding of the spec is correct, you can tell if it's a head fragment by checking if there's a link, meta, or style element inside, since those aren't allowed in the body.
Is there a practical way to do that? I haven't looked deep into the code yet.

The use case where noscript outside the body is needed comes up in rewriting, e.g. if I want to automatically insert a noscript into pages that have scripts with something like `Soup.parse "<noscript>Enable JS for full functionality</noscript>" |> Soup.append_child (document $ "body")`.

**Comment by aantron** [comment]
> If my understanding of the spec is correct, you can tell if it's a head fragment by checking if there's a link, meta, or style element inside, since those aren't allowed in the body.

This *should* be correct if HTML was easy to parse, but it's not, and that's not according to the spec. There is nothing about inferring context in the spec. The context has to be provided by the user of the parser that is specified in the spec.

What I have Markup.ml do right now is tokenize the fragment until it reaches the first start element token, and guess the context based on that. This is has nothing to do with the spec, but should be correct in most cases anyway. Markup.ml allows setting the context manually if it is known, which *is* according to spec.

The reason I don't do more lookahead to guess the context even "better" is because how the tokenizer works depends on the parser, i.e. there is full feedback both ways between the parser and the tokenizer. So, there is no good way to do lookahead except by running the parser. We could add backtracking, but this is even more speculative deviation that is likely to be a mistake, and also the more lookahead we use, the less Markup.ml remains a streaming parser.

I understand there are valid use cases, that's not an issue :)

If, in your code, you will know the context, you can use `Markup.parse_html ~context:(`Fragment "body")` together with `Soup.from_signals`.

**Comment by aantron** [comment]
The attached commit makes Markup.ml guess that `<noscript>` and `<script>` fragments are inside `<body>` by default, which improves parsing in the case in your message, and probably in most cases. See the new and changed tests.

Reflecting on the context more, I noted that a web browser, for example, never parses HTML without a context, AFAIK. It is always either parsing an entire document, or else it is parsing HTML as a consequence of a call to `innerHTML`, where the element `innerHTML` is called on serves as the context. In light of the present issue, I would guess that this arrangement is not an accident :)

We may have to eventually add a note to the Lambda Soup docs, and perhaps an optional `?context` parameter to `Soup.parse`. Even without it, however, it is still possible to parse with a context using Markup.ml directly and `Soup.from_signals`.

Would you like a speedy release of this change to opam?

**Comment by dmbaturin** [comment]
It would be nice to have this in opam indeed. There aren't many people building [soupault](https://opam.ocaml.org/packages/soupault/) from opam yet (it takes time to take over the world ;), but if you aren't working on anything else, I suppose this is worth a release.

Analytics setup snippets often have a noscript alternative, so people trying to include them in pages are quite likely to run into it (that's how the issue was discovered).
