### ISSUE TITLE
Where does html entity substitution take place?

### ISSUE THREAD

**Issue by sagotch** [aantron/markup.ml#57]
Hi.

I want to tweak markup so `&#91;` si returned as `&#91;` and not `[` but I can find where the replacement takes place so I can bypass it. Can you help?

**Comment by aantron** [comment]
It's done here:

https://github.com/aantron/markup.ml/blob/7e2adca8389543b8a7335a12c57bff38a797640a/src/html_tokenizer.ml#L191-L387

That function and its helpers implement [this part of the spec and follow-on sections](https://www.w3.org/TR/html52/syntax.html#character-reference-state). It looks like the sections have been slightly renumbered since the time when I wrote the code, they are off by ~3 here (i.e. 69 is now 72).

**Comment by sagotch** [comment]
That is what I looked at, but I have been confused by the fact that `91` is the actual codepoint of `]`, not only in `&#91;` -_-

I guees I can pre-process my input to escape `&` and it should be fine.
