### ISSUE TITLE
Add a newline after the doctype declaration

### ISSUE THREAD

**Issue by dmbaturin** [aantron/markup.ml#58]
When people write HTML by hand, traditionally they put a newline between the doctype declaration and the `<html>` tag.
With long doctypes of HTML 4.01 and XHTML 1.x, that was a necessity for readability I guess, but it still looks more aesthetically pleasing even with much shorter HTML5 doctype.

Markup.ml, however, outputs them on the same line: `<!DOCTYPE html><html>`.

**Comment by aantron** [comment]
The linked commit makes `Markup.pretty_print` insert a newline.

It's technically a breaking change, because it changes `Markup.pretty_print`'s signature from

```ocaml
([> content_signal ] as 'a, 's) stream -> ('a, 's) stream
```

to

```ocaml
([> content_signal | `Doctype of doctype ] as 'a, 's) stream -> ('a, 's) stream
```

This should affect primarily users of [`Markup.content`](https://github.com/aantron/markup.ml/blob/b4b59ae16e6bd802cd913cee853114ea70cfd079/src/markup.mli#L548-L550), but also potentially anyone who creates their own subtype streams. I suspect there are very few people who do either one of these things. I'll do a search in opam and on GitHub to try to get an estimate based on public code.

There may be other ways to implement and/or type this. However, I am leaning instead towards eliminating all this subtyping in the interface, and using just `signal` everywhere. That would be an even bigger breaking change, but I again suspect it will affect almost nobody. I opened #59 about that. After I do the opam search, I'm thinking to do #59, and then retag 1.0.0, as I don't want to release 2.0.0 right away, and I doubt anyone is yet relying on 1.0.0 :P
