### ISSUE TITLE
Invalid parsing of character entities in XML ?

### ISSUE THREAD

**Issue by occtyping** [aantron/markup.ml#65]
Hello,

it seems that by defaults, character entities are rendered as "U+nnnn" : 
```
open Markup
let s = (string "<a>&#1234;</a>") |> parse_xml |> signals |> to_list;;
```
renders : 
```
  [`Start_element (("", "a"), []); `Text ["U+1234"]; `End_element]
```
It does not seem that changing the ~encoding parameter of parse_xml or supplying a custom entity resolver has any impact. The problem is of course than afterwards, reparsing "U+1234" in `Text` elements is clumsy. The problem does not occur with the html parser.

**Comment by aantron** [comment]
Thanks for the report. I believe this is fixed by the above [commit](https://github.com/aantron/markup.ml/commit/ddb2d51e3189f549eeb1356855b6fbf960590ae2), which also adds a test case. The problem was that the entity parser, part of the XML tokenizer, was using a function for converting the Unicode code point that is meant for error messages, rather than for the actual output.

Would you like a speedy release to opam?

**Comment by occtyping** [comment]
Incredible reaction speed!
I can totally live with pinning the current trunk and waiting for a stable release later if you have other changes in flight.
Thanks a lot.

**Comment by aantron** [comment]
The fix should be out in Markup.ml 1.0.1, shortly after https://github.com/ocaml/opam-repository/pull/18868 gets merged.
