### ISSUE TITLE
Fail to parse url

### ISSUE THREAD

**Issue by craff** [aantron/markup.ml#72]
Url are not accepted by the html_tokenizer. 

To reproduce, just replace line 28 of "test_html_parser.ml" from
```
  |> Markup__Html_tokenizer.tokenize Error.ignore_errors
```
to
```
  |> Markup__Html_tokenizer.tokenize report
```

and `make test` yields
```
File "test/support/test_support.ml", line 70, characters 1-1:
Error: markup.ml:220:html.parser.links (in the code).

<a href="foo.com?bar=on&image=on">foo</a>
got "line 1, column 24: bad token '&image=' in attribute: unterminated entity reference followed by '='"
```

**Comment by craff** [comment]
I submitted a PR #73 for that.

**Comment by craff** [comment]
Hello

https://thisthat.dev/encode-uri-vs-encode-uri-component/ explains that there are 11 characters not encoded in Uri except when they are in the path or query values. 

Percent encoding does not work for query. In my patch I took exactly the attributes which have an uri type.

Cheers
Christophe 

Le 13 juillet 2023 03:30:52 GMT-10:00, Anton Bachin ***@***.***> a écrit :

**Comment by craff** [comment]
https://datatracker.ietf.org/doc/html/rfc3986#page-11 here is the precise RFC. I could implement it exactly to verify uri?

Le 13 juillet 2023 03:30:52 GMT-10:00, Anton Bachin ***@***.***> a écrit :

**Comment by craff** [comment]
I dig more that issue. First firefox and chromium accept non percent encoded delimiter in URI and delimiter are defined in RFC 3986, where it is clear that percent encoding is used for escape reserved characters in values. 

Nevertheless, this document:
https://www.w3.org/TR/REC-html40/appendix/notes.html#non-ascii-chars agrees with you. 

In the end I can live with both, feel free to close the issue and PR #73 or dig more the subject.

**Comment by craff** [comment]
And by the way, I don't know how browser manage to accept both kind of url, this should mess up their code ?

**Comment by craff** [comment]
And while digging, I learnt I could use, and it is recommended to use semicolumn for query ;-)

**Comment by aantron** [comment]
I'm not sure I understood you, but replying to what I think you mean.

The issue here is not percent encoding -- that is a separate step. After percent encoding or any other encoding applied to the URI, when the encoded URI is placed into an attribute value, it should be additionally encoded using HTML attribute encoding, which should, among other things, convert `&` to `&amp;`. Not doing so *can* work for most URLs, because the error is recoverable by the HTML parser. But if you have a URI like `http://foo.org/?a=1&amp=2` it will be misinterpreted if not HTML attribute encoded as `http://foo.org/?a=1&amp;amp=2`.

**Comment by aantron** [comment]
And, as you saw [here](https://www.w3.org/TR/REC-html40/appendix/notes.html#h-B.2.2), the document also recommends escaping. It's not really even recommended, but practically required, though if you are manually writing HTML you can get by without it because error recovery will save you as long as a query parameter name does not match one of the HTML entity names.

So I think there is nothing to fix for this issue on the Markup.ml side.

**Comment by craff** [comment]
Anton Bachin ***@***.***> writes:

> And, as you saw here, the document also recommends escaping. It's not really even recommended, but practically required, though if you are manually
> writing HTML you can get by without it because error recovery will save you as long as a query parameter name does not match one of the HTML entity
> names.
>
> So I think there is nothing to fix for this issue on the Markup.ml side.

Yes I agree. took me some time to understant all this, sorry.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.


--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu

Ce mail est signé avec pgp (Pièce jointe signature.asc, clef sur https://raffalli.eu/pgp)
This mail is signed with pgp (Attachment signature.asc, key  on  https://raffalli.eu/pgp)

**Comment by aantron** [comment]
Thanks! I'm going to close this issue, but feel free to discuss further if anything else comes up on it.

**Comment by craff** [comment]
I read the html specification [here](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2) and it says that the only restriction for & is about ambiguous ones, i.e. &toto;
where toto is not a defined character reference. Hence href="/path?x=1&y=2" is a perfectly valid attribute value as there is no semicolumn after the y:

> Attribute values are a mixture of [text](https://html.spec.whatwg.org/multipage/syntax.html#syntax-text) and [character references](https://html.spec.whatwg.org/multipage/syntax.html#syntax-charref), except with the additional restriction that the text cannot contain an [ambiguous ampersand](https://html.spec.whatwg.org/multipage/syntax.html#syntax-ambiguous-ampersand).

**Comment by aantron** [comment]
The HTML specification specifies a particular behavior for the tokenizer, including when it emits errors. The section you are citing is under *Writing HTML documents*, rather than parsing them. The rules for writing HTML documents are much simpler.
